################################################
################################################
## Dockerfile to run Mega-Linter (Quick mode) ##
################################################
################################################

##################
# Get base image #
##################
ARG MEGALINTER_BASE_IMAGE=nvuillam/mega-linter:latest
FROM $MEGALINTER_BASE_IMAGE

################################
# Installs python dependencies #
################################
COPY megalinter /megalinter
RUN python /megalinter/setup.py install

#######################################
# Copy scripts and rules to container #
#######################################
COPY megalinter/descriptors /megalinter-descriptors
COPY TEMPLATES /action/lib/.automation

###########################
# Get the build arguments #
###########################
ARG BUILD_DATE
ARG BUILD_REVISION
ARG BUILD_VERSION

#################################################
# Set ENV values used for debugging the version #
#################################################
ENV AUTHOR_NAME_EMAIL=$AUTHOR_NAME_EMAIL \
    AUTHOR_USERNAME=$AUTHOR_USERNAME \
    BUILD_DATE=$BUILD_DATE \
    BUILD_REVISION=$BUILD_REVISION \
    BUILD_VERSION=$BUILD_VERSION

ENV MEGALINTER_FLAVOR=all

#########################################
# Label the instance and set maintainer #
#########################################
LABEL maintainer=$AUTHOR_NAME_EMAIL \
      org.opencontainers.image.created=$BUILD_DATE \
      org.opencontainers.image.revision=$BUILD_REVISION \
      org.opencontainers.image.version=$BUILD_VERSION \
      org.opencontainers.image.authors=$AUTHOR_NAME_EMAIL \
      org.opencontainers.image.url="https://" + AUTHOR_USERNAME + ".github.io/mega-linter" \
      org.opencontainers.image.source="https://github.com/" + AUTHOR_USERNAME + "/mega-linter" \
      org.opencontainers.image.documentation="https://" + AUTHOR_USERNAME + ".github.io/mega-linter" \
      org.opencontainers.image.vendor=$AUTHOR_NAME_EMAIL \
      org.opencontainers.image.description="Lint your code base in any CI pipeline"
