# https://taskfile.dev
version: "3"

vars:
  # https://nvuillam.github.io/mega-linter/flavors/
  MEGA_LINTER_FLAVOR: terraform

tasks:
  default:
    deps: [check]

  setup:
    silent: true
    desc: test that mega-linter-runner is setup
    status:
      - test "$(uname -s)" = "Darwin"
      - test $(command -v npx)
      - test -f /Applications/Docker.app || echo "Failed to locate Docker.app"
    cmds:
      - echo "Please review mega-linter-runner prerequisites. See the README for details." && exit 1

  docker:
    silent: true
    deps: [setup]
    desc: test that docker is running
    status:
      - pgrep -f Docker.app
    cmds:
      - open -j /Applications/Docker.app # --args --env VAR (VAR should be formatted NAME=VALUE)
      - echo "Waiting for Docker to start up ..."
      - sleep 20

  git_crlf:
    silent: true
    desc: set git autcrlf config if necessary
    deps: [docker]
    status:
      - test "$(git config --global  -l | grep crlf)" = "core.autocrlf=false"
    cmds:
      - git config --global core.autocrlf false

  config:
    silent: true
    desc: test that mega-linter-runner has a config file
    deps: [git_crlf]
    status:
      - test -f .mega-linter.yml
    cmds:
      # perhaps instead of using the mega-linter built-in install 'wizard',
      # this task should copy in a Subsplash standard mega-linter config template
      - npx mega-linter-runner --install

  check:
    desc: check for lint and style issues
    deps: [config]
    cmds:
      # cleanup any older report content and run mega-linter
      - rm -rf ./report/
      - npx mega-linter-runner --flavor {{.MEGA_LINTER_FLAVOR}} -e 'LOG_LEVEL=INFO'

  fix:
    desc: fix 'easy' lint and style issues
    deps: [config]
    cmds:
      - npx mega-linter-runner --flavor {{.MEGA_LINTER_FLAVOR}} -e 'LOG_LEVEL=INFO' --fix
